Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
  
    # config.vm.provider "virtualbox"
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "384"]
    end
  
    # nomad boxes
    (1..3).each do |i|
      config.vm.define "nomad#{i}" do |nomad|
        nomad.vm.hostname = "nomad#{i}"
        nomad.vm.network "private_network", ip: "192.168.56.#{10+i}"
        nomad.vm.provision "shell", path: "scripts/install-hashicorp-repository.sh"
        nomad.vm.provision "shell", path: "scripts/install-consul.sh"
        nomad.vm.provision "shell", path: "scripts/install-nomad.sh"
        nomad.vm.provision "shell", path: "scripts/install-bash-env-consul.sh"
        nomad.vm.provision "shell", path: "scripts/install-bash-env-nomad.sh"
        nomad.vm.provision "shell", path: "scripts/config-consul-client.sh"
        nomad.vm.provision "shell", path: "scripts/config-nomad-server.sh"
        nomad.vm.provision "shell", path: "scripts/config-nomad-snapshot-agent.sh"
      end
    end
    (1..1).each do |i|
        config.vm.define "consul#{i}" do |consul|
          consul.vm.hostname = "consul#{i}"
          consul.vm.network "private_network", ip: "192.168.56.#{20+i}"
          consul.vm.provision "shell", path: "scripts/install-hashicorp-repository.sh"
          consul.vm.provision "shell", path: "scripts/install-consul.sh"
          consul.vm.provision "shell", path: "scripts/install-bash-env-consul.sh"
          consul.vm.provision "shell", path: "scripts/config-consul-server.sh"
        end
      end
  end