Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # config.vm.provider "virtualbox"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "384"]
  end

  # all nodes
  config.vm.provision "shell", path: "scripts/install-hashicorp-repository.sh"
  config.vm.provision "shell", path: "scripts/install-consul.sh"
  config.vm.provision "shell", path: "scripts/install-bash-env-consul.sh"
  config.vm.provision "shell", path: "scripts/config-dns-to-consul.sh"


  # consul
  (1..1).each do |i|
    config.vm.define "consul#{i}" do |consul|
      consul.vm.hostname = "consul#{i}"
      consul.vm.network "private_network", ip: "192.168.56.#{10+i}"
      consul.vm.provision "shell", path: "scripts/config-consul-server.sh"
    end
  end

  # Client
  config.vm.define "client1" do |client1|
    client1.vm.hostname = "client1"
    client1.vm.network "private_network", ip: "192.168.56.51"
    client1.vm.provision "shell", path: "scripts/install-fake-service.sh"
    client1.vm.provision "shell", path: "scripts/config-consul-client.sh"
    client1.vm.provision "shell", path: "scripts/config-app-web.sh"
   end

  config.vm.define "client2" do |client2|
    client2.vm.hostname = "client2"
    client2.vm.network "private_network", ip: "192.168.56.52"
    client2.vm.provision "shell", path: "scripts/install-fake-service.sh"
    client2.vm.provision "shell", path: "scripts/config-consul-client.sh"
    client2.vm.provision "shell", path: "scripts/config-app-api.sh"
  end
end
